### ISSUE TITLE
Script does not send emails past my filter, please fix this

### ISSUE THREAD

**Issue by PatrickOBoyle** [414owen/SpamPatrick#1]
Title.

**Comment by 414owen** [comment]
Yes, thank you Patrick, I completely see the problem and we are doing everything we can to fix it on our end.

I would however suggest that the root cause of the problem might be the filters themselves. Would you be able to disable them permanently? I'm perfectly happy to put in a pull request myself.

Thanks again,
The SpamPatrick® Team
